### ISSUE TITLE
Colors aren't displayed correctly

### ISSUE THREAD

**Issue by simplexidev** [simplexidev/sdevlibs#24]
When the application opens, the color isn't the selected green, but it's purple.

~When the color is changed to black (`#FF000000`), the resulting image turns gray (`#FF7F7F7F`).~

**Comment by tom-corwin** [comment]
No colors are displayed correctly, considering the ColorPicker is set to start as Blue, not Green or Purple.

What a mess...

**Comment by tom-corwin** [comment]
Still isn't displaying the correct colors on Windows. If I stop halving the alpha, it works fine.

**Comment by tom-corwin** [comment]
This needs looked at again after merging `api-changes`. This might have just been nothing.

If anyone could confirm this, that would be appriciated, because I need a sanity check here.

**Comment by simplexidev** [comment]
Out of scope for new roadmap.
