### ISSUE TITLE
Possible MDI implimentation? I don't think libui supports it natively.

### ISSUE THREAD

**Issue by Shadowblitz16** [simplexidev/sdevlibs#38]
**Is your feature request related to a problem? Please describe.**
No its more of a sad reality of the modern world and of nostalgia.
But in reality it's about game editors and size limitation of small single monitors. 

**Describe the solution you'd like**
MDI (M)ultiple (D)ocument (I)nterface.

Would it be possible to hack in multiple document interface if it isn't too hard?
I don't think libui supports it so if it's even possible it would be a hacky solution.

**Describe alternatives you've considered**
Many many other GUI libraries.

**Additional Information**
Mac uses a totally different ui layout.
It could probably just use separate windows and close them when the main window closes.

**Comment by tom-corwin** [comment]
I like this idea, and was thinking about it a while back while working on this project. 
I'm linking your issue from libui (andlabs/libui#475), as well as another one for child windows (andlabs/libui#137).

**Comment by simplexidev** [comment]
Out of scope for new roadmap.
